// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgFseFWeMRjAbYfXXijCs402ApCs3Qtj8',
    appId: '1:143290857126:web:d128abd0cfae85d54fa667',
    messagingSenderId: '143290857126',
    projectId: 'gcommerce-254ec',
    authDomain: 'gcommerce-254ec.firebaseapp.com',
    databaseURL: 'https://gcommerce-254ec-default-rtdb.firebaseio.com',
    storageBucket: 'gcommerce-254ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeJ30v513ryzxis9iBFlnTGm2G-do9kl8',
    appId: '1:143290857126:android:97ec4f0ba8ad4eea4fa667',
    messagingSenderId: '143290857126',
    projectId: 'gcommerce-254ec',
    databaseURL: 'https://gcommerce-254ec-default-rtdb.firebaseio.com',
    storageBucket: 'gcommerce-254ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7TmO5ri3-Bqi1LPKB60O0H_CATuK8xqI',
    appId: '1:143290857126:ios:d1b22091e6b9deca4fa667',
    messagingSenderId: '143290857126',
    projectId: 'gcommerce-254ec',
    databaseURL: 'https://gcommerce-254ec-default-rtdb.firebaseio.com',
    storageBucket: 'gcommerce-254ec.appspot.com',
    iosClientId: '143290857126-plmjt4alen9c4gj72av6dtc62cjl3pon.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestionCommercial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7TmO5ri3-Bqi1LPKB60O0H_CATuK8xqI',
    appId: '1:143290857126:ios:d1b22091e6b9deca4fa667',
    messagingSenderId: '143290857126',
    projectId: 'gcommerce-254ec',
    databaseURL: 'https://gcommerce-254ec-default-rtdb.firebaseio.com',
    storageBucket: 'gcommerce-254ec.appspot.com',
    iosClientId: '143290857126-plmjt4alen9c4gj72av6dtc62cjl3pon.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestionCommercial',
  );
}
